version: '3.5'
services:
  guitar.shop.mongodb:
    image: mongo
    restart: always
    container_name: guitar.shop.mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: guitar-shop

    ports:
      - 27017:27017

    volumes:
      - guitar.mongo.shop:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/guitar-shop --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  guitar.shop.mongo.ui:
    image: mongo-express
    restart: always
    container_name: guitar.shop.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@guitar.shop.mongodb:27017/

volumes:
  guitar.shop.mongo:
