
# Пользователи
## Создание нового пользователя (5.6)
POST http://localhost:4000/users/create HTTP/1.1
Content-Type: application/json

{
  "name": "qwerty",
  "email": "qwerty@mail.ru",
  "password": "qwerty"
}
###

## Вход в закрытую часть приложения (5.7)
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "admin"
}
###

## Проверка состояния пользователя (5.8)
GET  http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlhdCI6MTY4NTcwNjQ5MCwiZXhwIjoxNjg1ODc5MjkwfQ.skRtTPK1AMs93AiChZ8EAXjlDwVOGkPgnHAvhKMB8zY

###


# Товары
## Создание нового товара (5.1)
POST http://localhost:4000/products/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NjAyMjM3MCwiZXhwIjoxNjg2MTk1MTcwfQ.tVZ57OdwIEELmlIgIAQW3N7ielJtEigsNb-hsHRx8s0
 

{
  "title": "Гитара 99999",
  "description": "Отличнейшая электро гитара",
  "addDate": "2023-01-25T08:20:40.283Z",
  "guitarType": "электро",
  "article": "3VRS14858383D",
  "stringsCount": 7,
  "price": 3900
}
###

## Редактирование товара (5.2)
PATCH http://localhost:4000/products/647a16eb20b2dee85cf73a7d/edit HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NTcyMjIzMCwiZXhwIjoxNjg1ODk1MDMwfQ.qL-XNlSHHzDSLmZEAy72nOpDbw90YnGA47CGLMTJowk

{
  "guitarType": "акустика"
}
###

## Удаление товара (5.3)
DELETE  http://localhost:4000/products/647a16eb20b2dee85cf73a7d/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NTcyMjIzMCwiZXhwIjoxNjg1ODk1MDMwfQ.qL-XNlSHHzDSLmZEAy72nOpDbw90YnGA47CGLMTJowk

###

## Получение списка товаров (5.4)
GET http://localhost:4000/products/filter?guitarType=электро&sortPrice=asc&limit=7&page=0 HTTP/1.1
Content-Type: application/json

###

## Получение полного списка товаров (5.4)
GET http://localhost:4000/products HTTP/1.1
Content-Type: application/json

###

## Получение детальной информации по товару (5.5)
GET http://localhost:4000/products/647af3a8d40f1e2d592533cf HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NTk4NjY4MSwiZXhwIjoxNjg2MTU5NDgxfQ.WzG92e9KAaHp7yIKcFSEX4-AE_tDBwUTDa3_t-UIAYI

###


## Загрузка фото для товара
POST http://localhost:4000/products/647a1b1423eacbef63b8cc63/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6IjY0Nzk4ZDE0MDU3MTY1NTcyMzM4ZmNiYSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NTcyMjIzMCwiZXhwIjoxNjg1ODk1MDMwfQ.qL-XNlSHHzDSLmZEAy72nOpDbw90YnGA47CGLMTJowk

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="ukulele.jpeg"
Content-Type: image/png

< ./mocks/img/ukulele.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###